# Generated by Django 4.2.7 on 2023-12-02 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_alter_eventregistration_usere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createevent',
            options={'ordering': ['id'], 'verbose_name': 'Create Event', 'verbose_name_plural': 'Create Events'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['id'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='userE',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
